version: '3.9'

services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_DB: "oggettoCase"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  web-api:
    depends_on:
      - postgres
    ports:
      - 8000:80
    environment:
      - ASPNETCORE_URLS=http://+
    build:
      context: .
      dockerfile: ./Dockerfile
      
volumes:
  dbdata: